### ISSUE TITLE
Add signing of published OCI images with cosign

### ISSUE THREAD

**Issue by devantler** [devantler-tech/.github#10]
### Description

The published Homelab OCI images should be signed with cosign as part of the `publish.yaml` pipeline.

Avisi Cloud provides [a guide](https://github.com/avisi-cloud/cosign-tutorial) for the purpose

### Tasklist

- [ ] devantler-tech/.github#9
- [ ] devantler-tech/.github#8
- [ ] devantler-tech/.github#7
