### ISSUE TITLE
Create a Repo for Backstage and set it up in `devantler/homelab`

### ISSUE THREAD

**Issue by devantler** [devantler-tech/.github#5]
**Tasklist:**

- [ ] devantler-tech/.github#4
- [ ] devantler-tech/.github#3
- [x] devantler-tech/issue-tracker#42
- [x] devantler-tech/issue-tracker#43
